name: market
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  auto_route: ^7.4.0
  cloud_firestore: 4.8.0
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  firebase_core: 2.13.1
  flutter:
    sdk: flutter

  flutter_animate: ^4.1.1+1
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.6
  hooks_riverpod: ^2.3.6
  json_annotation: ^4.8.1

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
