// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhnMqLAKbgP5NrAgpnZAdi7cScxjwPNDk',
    appId: '1:1089356401281:android:7af5f29527dc75b5c91b80',
    messagingSenderId: '1089356401281',
    projectId: 'market-f836b',
    storageBucket: 'market-f836b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsHBNNTWD-D6tIqsmpNRXYd9qaIWrj0VE',
    appId: '1:1089356401281:ios:fcec28f7af875ef2c91b80',
    messagingSenderId: '1089356401281',
    projectId: 'market-f836b',
    storageBucket: 'market-f836b.appspot.com',
    iosClientId: '1089356401281-dqk8oa0r4t0rhfb2eoh9hh3qldsns920.apps.googleusercontent.com',
    iosBundleId: 'com.deamdeveloper.market',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsHBNNTWD-D6tIqsmpNRXYd9qaIWrj0VE',
    appId: '1:1089356401281:ios:f2a85eb6ef2db289c91b80',
    messagingSenderId: '1089356401281',
    projectId: 'market-f836b',
    storageBucket: 'market-f836b.appspot.com',
    iosClientId: '1089356401281-13kdv8o6lsreknvd09ef6dhp5cilb260.apps.googleusercontent.com',
    iosBundleId: 'com.deamdeveloper.market.RunnerTests',
  );
}
